### ISSUE TITLE
Choropleth Testing troubles

### ISSUE THREAD

**Issue by Travmatth** [PHLDroplet/phillydroplet-client#16]
**Testing Error**
```
 FAIL  src/Map/__tests__/Choropleth.spec.js                                                                                                             [15/15]
  ● Choropleth › should render

    TypeError: Cannot read property '_controlCorners' of undefined
      
      at Class.extend.addTo (node_modules/leaflet/dist/leaflet-src.js:4613:19)
      at LegendControl.componentDidMount (src/Map/Components/Legend.jsx:40:64)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:76:22)
      at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
      at ReactReconcileTransaction.TransactionImpl.closeAll (node_modules/react-dom/lib/Transaction.js:206:25)
      at ReactReconcileTransaction.TransactionImpl.perform (node_modules/react-dom/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.TransactionImpl.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object.ReactMount._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:320:18)
      at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.ReactMount.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.ReactTestUtils.renderIntoDocument (node_modules/react-dom/lib/ReactTestUtils.js:79:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:187:26)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Object.<anonymous> (src/Map/__tests__/Choropleth.spec.js:49:39)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

  Choropleth
    ✕ should render (58ms)
    ○ skipped 1 test

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 skipped, 2 total
Snapshots:   1 passed, 1 total
Time:        6.233s
Ran all test suites matching /src/Map/__tests__/Choropleth.spec.js/.

Active Filters: filename /src/Map/__tests__/Choropleth.spec.js/

console.log src/Map/Components/Choropleth.jsx:36
    {}

console.log src/Map/Components/Legend.jsx:40
    context:  { map: undefined }


```
**src/Map/__tests__/Choropleth.spec.js**
```
/* eslint-env jest */

import React, { Component } from 'react';
import PropTypes from 'prop-types';
import enzyme, { mount } from 'enzyme';
import toJson from 'enzyme-to-json';
import * as ReactLeaflet from 'react-leaflet';
import Choropleth, { geoJsonStyle } from 'src/Map/Components/Choropleth';

let enzymeWrapper;

jest.mock('react-leaflet', () => {
  // react-leaflet uses `style`, while vanilla components use `styles`
  const modify = props => {
    const { style, ...nextProps } = props;
    nextProps.styles = style;
    return nextProps;
  };

  return {
    ...require.requireActual('react-leaflet'),
    Map: props => <div {...modify(props)} />,
    GeoJSON: props => <div {...modify(props)} />,
    TileLayer: props => <div {...modify(props)} />,
  };
});

class Mock extends Component {
  constructor(props) {
    super(props);
  }
}

describe('Choropleth', () => {
  beforeEach(() => {
    enzymeWrapper = mount(<Choropleth />, {
      options: {
        context: {
          map: Mock,
        },
        childContextTypes: {
          map: PropTypes.element,
        },
      },
    });
  });

  afterEach(() => {});

  it.only('should render', () => {
    expect(toJson(enzymeWrapper)).toMatchSnapshot();
  });
});
```
**src/Map/Components/Legend.jsx**
```
import React, { Component } from 'react';
import { MapControl } from 'react-leaflet';
import Dropdown from './Dropdown';
import ReactDOM from 'react-dom';

const control = (onClick) => (
  <div className='leaflet-control-button button' onClick={onClick}>
    Legend
  </div>
);

class LegendControl extends MapControl {
  componentDidMount() {
    console.log('context: ', this.context)
    this.leafletElement.addTo(this.context.map)
    this.leafletElement._container.classList.add('extend-leaflet-control');
  }

  createLeafletElement = (props: Object) => {
    const { onClick } = props;
    const legend = L.control({ position: 'topleft' });

    legend.onAdd = function (map) {
      let div = L.DomUtil.create('div', '');
      ReactDOM.render(control(onClick), div);
      return div;
    };

    return legend;
  }
}
...
export { Legend, LegendControl };
```
**src/Map/Components/Choropleth.jsx**
```
import React, { Component } from 'react';
import chroma from 'chroma-js';
import * as topojson from 'topojson';
import { Map, GeoJSON } from 'react-leaflet';
import { LegendControl } from './Legend';
import neighborhoodLayer from 'assets/Neighborhoods_Philadelphia.json';

const PHILA_COORDS = [40, -75.125885];
const xColorScale = chroma.scale(['e8e8e8', 'c85a5a']);
const yColorScale = chroma.scale(['e8e8e8', '64acbe']);


const geoJsonStyle = (variable, scale) =>
  feature => ({
    color: 'grey',
    opacity: 1,
    weight: 1,
    fillColor: feature.properties[variable]
  });

class Choropleth extends Component {
  state = {
    features: null,
  }

  constructor(props) {
    super(props);
  }

  componentWillMount() {
    console.log(this.context)
  }

  componentDidMount() {
    this.setState({ features: [
      ...topojson.feature(
        neighborhoodLayer,
        neighborhoodLayer.objects.collection
      ).features,
    ]});
   }

  render() {
    const { props: { className, variable, onClick, }, state: { features } } = this;
    const xStyle = geoJsonStyle(variable, xColorScale);

    return (
      <div className={`${className} droplet-section`}>
        <Map center={PHILA_COORDS} className='droplet-map' zoom={11}>
          <LegendControl onClick={onClick} map={Map}/>
          {
            features
              ? features.map((feat, i) => (
                  <GeoJSON style={xStyle} key={i} data={feat}/>
                ))
              : null
          }
        </Map>
      </div>
    );
  }
}

export default Choropleth;
export { geoJsonStyle };
```

**Comment by Travmatth** [comment]
```
    TypeError: Cannot read property '_controlCorners' of undefined
      
      at Class.extend.addTo (node_modules/leaflet/dist/leaflet-src.js:4613:19)
```

Error stems from `src/Map/Components/Legend.jsx`, with the lines:
<pre>
class LegendControl extends MapControl {
  componentDidMount() {
    console.log('context: ', this.context)
    <b>this.leafletElement.addTo(this.context.map)</b>
    this.leafletElement._container.classList.add('extend-leaflet-control');
  }

  createLeafletElement = (props: Object) => {
    ...
  }
}
</pre>
because `this.context.map === undefined`
